"use client";

import { useState } from "react";
import { useAuth } from "@clerk/nextjs";
import { apiFetch } from "../lib/api";

interface Explanation {
  status: "pending" | "succeeded" | "failed";
  response: string | null;
  error: string | null;
  model: string;
  createdAt: string;
}

// ARCHITECTURE.md §9's guardrail: AI output must be clearly labeled as such, distinct
// from the deterministic findings above it on the page -- this panel never presents the
// explanation as if it were itself a scoring signal.
export function AiExplanationPanel({
  findingId,
  initialExplanation,
}: {
  findingId: string;
  initialExplanation: Explanation | null;
}) {
  const { getToken } = useAuth();
  const [explanation, setExplanation] = useState(initialExplanation);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleGenerate() {
    setGenerating(true);
    setError(null);
    try {
      const token = await getToken();
      const result = await apiFetch<Explanation>(`/api/findings/${findingId}/explain`, token, { method: "POST" });
      setExplanation(result);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setGenerating(false);
    }
  }

  return (
    <section className="mt-8">
      <div className="flex items-center gap-2">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-gray-500">AI Explanation</h2>
        <span className="rounded border border-purple-600/40 bg-purple-600/20 px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-purple-300">
          AI-generated
        </span>
      </div>

      {explanation?.status === "succeeded" && (
        <div className="mt-3 rounded border border-gray-800 p-4">
          <p className="text-sm text-gray-300">{explanation.response}</p>
          <p className="mt-2 text-xs text-gray-600">
            Generated by {explanation.model} on {new Date(explanation.createdAt).toLocaleString()} — narrates the deterministic score
            above, does not set it.
          </p>
          <button
            onClick={handleGenerate}
            disabled={generating}
            className="mt-3 text-xs text-blue-400 hover:underline disabled:opacity-50"
          >
            {generating ? "Regenerating…" : "Regenerate"}
          </button>
        </div>
      )}

      {explanation?.status === "pending" && (
        <p className="mt-3 text-sm text-gray-500">Generating… refresh in a moment.</p>
      )}

      {(!explanation || explanation.status === "failed") && (
        <div className="mt-3">
          {explanation?.status === "failed" && (
            <p className="text-sm text-red-400">Last attempt failed: {explanation.error}</p>
          )}
          <button
            onClick={handleGenerate}
            disabled={generating}
            className="mt-2 rounded border border-gray-700 px-3 py-1.5 text-sm text-gray-200 hover:bg-gray-800 disabled:opacity-50"
          >
            {generating ? "Generating…" : "Generate AI explanation"}
          </button>
        </div>
      )}

      {error && <p className="mt-2 text-sm text-red-400">{error}</p>}
    </section>
  );
}
