"use client";

import { useState } from "react";
import { useAuth } from "@clerk/nextjs";
import { apiFetch } from "../lib/api";

interface Explanation {
  status: "pending" | "succeeded" | "failed";
  response: string | null;
  error: string | null;
  model: string;
  createdAt: string;
}

// ARCHITECTURE.md §9's guardrail: AI output must be clearly labeled as such, distinct
// from the deterministic findings above it on the page -- this panel never presents the
// explanation as if it were itself a scoring signal.
export function AiExplanationPanel({
  findingId,
  initialExplanation,
}: {
  findingId: string;
  initialExplanation: Explanation | null;
}) {
  const { getToken } = useAuth();
  const [explanation, setExplanation] = useState(initialExplanation);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleGenerate() {
    setGenerating(true);
    setError(null);
    try {
      const token = await getToken();
      const result = await apiFetch<Explanation>(`/api/findings/${findingId}/explain`, token, { method: "POST" });
      setExplanation(result);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setGenerating(false);
    }
  }

  return (
    <section className="card mt-6 p-5">
      <div className="flex items-center gap-2">
        <h2 className="label">AI explanation</h2>
        <span className="rounded-md border border-purple-200 bg-purple-50 px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-purple-700">
          AI-generated
        </span>
      </div>

      {explanation?.status === "succeeded" && (
        <div className="mt-3 rounded-md border border-line bg-surface p-4">
          <p className="text-sm text-ink-muted">{explanation.response}</p>
          <p className="mt-2 text-xs text-ink-faint">
            Generated by {explanation.model} on {new Date(explanation.createdAt).toLocaleString()} — narrates the deterministic score
            above, does not set it.
          </p>
          <button onClick={handleGenerate} disabled={generating} className="btn-ghost mt-3 px-0 text-xs">
            {generating ? "Regenerating…" : "Regenerate"}
          </button>
        </div>
      )}

      {explanation?.status === "pending" && (
        <p className="mt-3 text-sm text-ink-subtle">Generating… refresh in a moment.</p>
      )}

      {(!explanation || explanation.status === "failed") && (
        <div className="mt-3">
          {explanation?.status === "failed" && (
            <p className="text-sm text-red-600">Last attempt failed: {explanation.error}</p>
          )}
          <button onClick={handleGenerate} disabled={generating} className="btn-secondary mt-2">
            {generating ? "Generating…" : "Generate AI explanation"}
          </button>
        </div>
      )}

      {error && <p className="mt-2 text-sm text-red-600">{error}</p>}
    </section>
  );
}
